version: '3'
services:
  app:
    container_name: news_api
    restart: always
    build: .
    ports:
      - '3311:3311'
    links:
      - mongo
    volumes: ['./:/usr/src/app']
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
